### PR TITLE
Add seed modification possibility

### PR DESCRIPTION
**Pull request by LordHansCapon**
UCP patcher now creates a ```gameseeds``` folder in the SHC root direction in which match seeds will be stored.

There are 2 options in this mod:
- the ```gameseeds/live``` file is read and the seed will be used in every match (_if found_).
- the game saves seeds in the ```gameseeds``` folder at the start of every match. These seed files are only created if the ```gameseeds/live``` file is not found, the filenames are the seed names (_a random number_) and their content is the same number.

**Game created seed file:**
image
**Its content:**
image

**Test build:**
https://we.tl/t-CJetMYnwu7

### CODE REVIEW

**Comment by Krarilotus** [comment]
testing the patcher:
- the top option sets two suboptions. Please make them radioboxes, so only one can be set  at a time! (setting both makes no sense...)
- there is no obvious description about how this 'live' file should look like, nor which kind of format it should have (maybe make the description a bit more verbose on how the seed is a document without any file ending, or we could provide a sample file with the release?)
- also make the description maybe more verbose on what the seed does like:

The seed is used to generate random numbers throughout the game, leading to the same game everytime, if the settings and input isn't changed.

other than that works great!!
I might do the description stuff tomorrow, but the boxes should be fixed hopefully!

**Comment by Krarilotus** [comment]
-Enable Game Seed
Setting the Game seed will allow AI-only games to play out the same way if the same map settings are used.
For player-AI games, it will ensure the same start conditions in the map (AIV selection for example) 
To set the game seed, enable this option and create a file called 'live' with a 6 digit number in the game install/gameseeds directory.
--Save game seeds
This option will save the seed from games that do not have a live seed set, so you can rename them to 'live' in order to recreate the match afterwards.

prefered behavior: have only one box with one suboption box, main box tick means same as now first suboption ticked. subbox ticked, means save enabled.

**Comment by gynt** [comment]
Currently, both the host and the client need to have this patch installed and the same seed set to make it work in multiplayer.
Normally, in multiplayer, the seed is shared after it is generated based on the current computer time before the game is launched.
I suggest as an improvement to hijack the function at 0x0046a740 (which sets the time based seed).
This will probably make it work in multiplayer too.

**Comment by Krarilotus** [comment]
Conversation from Discord for this change:

[23:22] Krarilotus: i now changed the description for the seed change option to GRhin's suggestion, however, while testing this more and more, i noticed, that you need to restart the game to ensure to get exactly the same game every time. Which is still better than nothing, like i would still want this option anyways, but it concerns me, that we might have missed something with the random number generator in the game.

Any ideas how we could fix this?
@gynt i know you were also working with this seed change, did you notice soemthing similar? And if so, how did you circumvent this, like do you have any idea how we could get this working without a game restart?
[23:40] Heroesflorian: Phrased differently: Without restarting the game, when re-running a single skirmish match a couple times, the match and endscreen statistics differ in each subsequent run. 
But when then restarting the game and doing the same again, that will result in the same sequence of matches / endscreen statistics being generated as for the previous game session.
[23:42] Heroesflorian: So it seems the match seed / match RNG is derived from a seed that is set when starting the game (not match) and does not get reset after a match.
[23:43] Heroesflorian: Oh, and... @Krarilotus were SHC and SHC-E differing with same seed or not?
[23:44] Krarilotus: yes
[23:44] Krarilotus: SHC and SHC-E produced different games with the same seed

**Pull request merged**
