### PR TITLE
Repointing https://github.com/Sh0wdown/UnofficialCrusaderPatch/pull/675

### PR DESCRIPTION
**Pull request by patel-nikhil**
# (Non-exhaustive) Changeset

## Language

- Language can now be changed while on the Main Window by selecting Option -> _&lt;Desired Language&gt;_ from the shown dropdown

## Path Selection

- Path selection can now be made both in the startup window and the Main Window using a dropdown with optional autocomplete, or by clicked `Browse` button
- On the startup window the `OK` button will not be clickable until a valid path is selected
- When a configuration file is loaded, and loading will result in a change of path (based on the user's _Preferences_) then a message box with options `Yes`, `No`, `Cancel` will be shown asking the user whether they wish to change the path

## Configuration

- UCP will continue to load the existing ucp.cfg format
- UCP is able to export the configuration from the Main Window by clicking File -> Save Config
  - The configuration will be exported in json format
- UCP is able to load a configuration from the Main Window by clicking File -> Load Config
  - The configuration to load should be in json format

- Configuration is handled in separate but similar manner by the UnofficialCrusaderPatchCLI.exe and UnofficialCrusaderPatchGUI.exe
  - For UnofficialCrusaderPatchGUI:
    - If `ucp.json` file exists in same directory as the UnofficialCrusaderPatchGUI.exe it will be loaded on startup
    - If `ucp.json` does not exist and _Preferences_ file contains key `mostRecentConfiguration` with value belonging to a valid filename then this configuration will be loaded
    - If neither of the above is true and `ucp.cfg` exists then this configuration will be loaded
    - If no configuration is present the UCP will load with an empty configuration
  - For UnofficialCrusaderPatchCLI:
    - If `--cfg=<filename>` is specified then the file pointed to will be used
    - If `--cfg` argument is not specified then `ucp.json` will be used if present in same directory
    - If neither of the above is true and `ucp.cfg` is present then the `ucp.cfg` will be loaded
    - If no configuration is present then the `Configuration file not found` will be written to console

## Preferences 
The _Preferences_ file is expected to contain the following keys and is not meant to be shared between users. Format is json with keys and values as follows:
- `hash`: _string_ - unique to a computer
- `path`: _string_ -- path to SHC installation folder
- `mostRecentConfiguration`: _string_ - used as defined in the **Configuration** section, this is updated only when a configuration is **loaded** and not when a configuration is saved
- `knownPaths`: _list&lt;string&gt;_ - list of previously selected paths, used in path selection dropdown, updated when a new path is selected
- `preferPathInConfig`: boolean - when present and set to `true` then UCP will use the path from the loaded config file, if the contained path is valid and the `hash` value of the config matches the `hash` value in the _Preferences_ file
- `language`: string - language to be used by the UCP, automatically updated when changed in the GUI
- `autosave`: boolean - when present and `true` then changes made in the GUI will be automatically written to `ucp.json` file.

# Implementation Details

### Location

- Localized strings for individual changes and GUI elements are now located within the UnofficialCrusaderPatchGUI project
- Instead of text files xaml resource files (in xml format) are used with format `<system:String x:Key="identifier">value</system:String>` where `identifier` is the key for retrieving the localized string from the GUI element, and `value` is the display value

### Using localized strings
- Within the GUI localized strings are used via the following example markup code `{DynamicResource ui_Bugfix}`

### Misc
- Preferred language is stored in the _Preferences_ file
- The strings for descriptions for AIC, AIV, StartTroop, StartResource changes are parsed and retrieved by the UnofficialCrusaderPath.dll
  - It is the responsibility of the content creator (UCP team for embedded content) to provide descriptions in the correct format (unchanged from v2.14)

## Configuration

The json schema for the configuration file can be found at this location: https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/5470888/configschema.zip

## Backend - UnofficialCrusaderPatch.dll

Class `ModAPIContract` provides the API for interacting with the UnofficialCrusaderPatch library

Methods:
- `ListAICConfiguration`: List&lt;AICConfiguration&gt;
  - Reads embedded AIC files and AIC files in `resources\aic` folder and returns an `AICConfiguration` object containing: { Identifier, CharacterList, CustomCharacterList, Description }

- `SetAICConfiguration`
  - Sets the AIC configuration value based on the object provided
  - The parameter can be of type `String`, `Dictionary<string, object>[]`, `List<AICConfiguration>`
    - When string, it must correspond to the AIC filename (without extension)

- `ListAIVConfiguration`: List&lt;AIVConfiguration&gt;
  - Reads embedded AIV files and AIV folders in `resources\aiv` folder and returns a list of `AIVConfiguration` objects containing: { Identifier, Description }

- `SetAIVConfiguration`
  - Sets AIVConfiguration using value provided

- `ListStartResourceConfigurations`: Dictionary&lt;string, StartResourceConfiguration&gt;
  - Reads embedded StartResource json files and files in `resources\goods` folder and returns a list of `StartResourceConfiguration` objects containing: { Identifier, Description }

- `SetStartResourceConfiguration`
  - Sets StartResourceConfiguration using value provided

- `ListStartTroopConfigurations`: Dictionary&lt;string, StartTroopConfiguration&gt;
  - Reads embedded StartTroop json files and files in `resources\troops` folder and returns a list of `StartTroopConfiguration` objects containing: { Identifier, Description }

- `SetStartTroopConfiguration`
  - Sets StartTroopConfiguration using value provided

- `ListChanges`: Dictionary&lt;string, IEnumerable&lt;string&gt;&gt;
  - Returns the list of generic changes
  - The dictionary key is the Mod identifier, and the values are the list of identifiers for the Changes within the Mod

- `SetModValues`, `SetModExtremeValues`: IEnumerable&lt;ChangeConfiguration&gt;
  - Applies to Mod.Change and Mod.ExtremeChange respectively
  - Enables each Mod identified by the ChangeConfiguration, and contained SubChanges for - setting Change parameter value as applicable
  - Disables all Mods and Changes not specified

- `Install`: UCPConfig, overwrite, graphical
  - Installs the UnofficialCrusaderPatch
  - UCPConfig specifies the configuration to use
  - Installs AIV as specified in the _AIV Installation_ section (if included in the UCPConfig)
  
  - If the Crusader exe is present, UCP is installed to it
    - Installs AIC, StartResources, StartTroops, GenericMods (as included in the UCPConfig)

  - If the Extreme exe is present, UCP is installed to it
      - Installs AIC, StartResources, StartTroops, GenericMods (as included in the UCPConfig)

## AIV Installation

  - Installs AIV files first as follows, note that these steps and checks are in sequential order:
    - If the same AIV files exist in the SHC installation, and the UCP path then no action is taken, _AIV installation complete_
    - If `overwrite` is specified and `true` then all AIV files in the SHC installation folder will be deleted and new AIV files copied to the SHC installation folder, _AIV installation complete_
    - If an existing subfolder named `original` does not exist in the SHC installation `aiv` folder
      - Create subfolder `original`
      - Copy all files from SHC `aiv` folder to `original` folder
      - Copy new AIV folder contents to SHC `aiv` folder
    - If subfolder `original` exists in the SHC installation `aiv` folder:
      - If files in the SHC `aiv` folder and `original` folder are identical, delete all AIV files from the `aiv` folder
      - If the files are different:
        - If parameter `graphical` is true:
          - UnofficialCrusaderPatch has been called by UnofficialCrusaderPatchGUI, show MessageBox with prompt `aiv_prompt`. If `Yes` then delete AIV files from `original` and write AIV from SHC `aiv` folder to `original` folder. If `No` then delete AIV from SHC `aiv` folder. If `Cancel` throw an Exception and install fails with no modifications made.
    - The final step of all paths (where no exception is thrown) is copying the embedded AIV files or external AIV folder content to the SHC `aiv` folder

## Uninstallation

Restores the original Crusader/Extreme exe's (saved as `Stronghold Crusader.exe.ucp_backup` and `Stronghold_Crusader_Extreme.exe.ucp_backup` where present) - unchanged behaviour

[TODO!!] Restores AIV from the `original` subfolder of the SHC `aiv` folder, when `original` subfolder is present and non-empty

### CODE REVIEW

**Comment by patel-nikhil** [comment]
All the previously mentioned todos are done, with some being specified to be added in a separate pull request to avoid additional complexity in reviewing and merging. Those include export of resource files, refreshing the view for resource files, and remaining translations.

**Comment by CIO61** [comment]
here are some simple tests i've run so far

- open up GUI +
- select a path +
- try selecting some options, check em uncheck em +

- try uninstall without .ucp_backup 
	- app doesnt do anything(as it shouldnt), **but gives no warning either**

- move ucp_backup to folder, then redo uninstall 
	**- app silently does it but theres no feedback!**

- try to save config 
	**- dialog doesnt know the filetype! 
	- and causes crash! (you can not save config)**

- try to load an improper config
	- **latest config gets updated, app cannot be lauched ever again**(unless user removes the wrong .json file from existence/or modifies prefs.json)

**Comment by Krarilotus** [comment]
https://github.com/patel-nikhil/UnofficialCrusaderPatch/actions?query=workflow%3A%22UCP+Build%22 newest testbuild can be found here!

**Comment by Krarilotus** [comment]
tests so far:
(no initial preferences in place)

- opening the GUI does work without error +
- ok greyed out, typing in random letters doesn't work, as intended +
-> also, only One of the executeables (extreme and normal Crusader) were required to make the OK button come up? Is the **OR functionality** intended? (typed in different paths, and remopved one or two executeables)
- browse path works +
-> selecting no paths works +
-> selecting paths also saves them into the bottom as soon as the path was confirmed to have one exe as defined (also now has my v1.1 version safed, how do i get it out of there? Need to open pref......) +

**Then clicking cancel:**
**error dump gets created with "System.NullReferenceException:"**

**- config fiddeling does the same things as described above by CIO**
- opening multiple windows of the patcher works +
-> but it doesn't show me the selected options from the other window, where i already made changes?!
**- it also doesn't remember any optiosn ticked, if closed completely and opened again, the config just straight up seems to not work at this point**

_moving on to the pather window part..._
image

- there is no seperation of the explanation text from the option, making it hard to see where it starts and ends. I feel like this was better before, with a slightly darker background window behind the explanatory text and extra options (like a slider/more option tickboxes)

- setting subbox options sets the correspondig main tickbox, +
- unticking main box, resets all subboxes and sliders. +
- **selecting deactivate demolishing for money of AI lords** does now autoselect all 3 options. Default before was just the first box. This would make sense to change to the first two boxes in my opinion, but just doing the default from before would still be better than tickign all three!**
- **Increase Rate of attacktroops now lets you choose both options at once. But only one can be applied!!! (either flat value or percentage)**
-> also selects autoamtically both at once with ticking the main box, which is definitly an error!
- just installing with a few options ticked, it seems to do nothing? But then also the _backup exe is created, so there must be something going on. **But no progress bar?**
- **Color change of player 1 keeps the color selected, even with the main box unticked**
- **AIV sets have no description? Seems like the localization linking broken there**
- AIC description texts still show
- no warning for multiselect
- starttroops and startresources description show

Now moving on to more installation tests:
- installing with no boxes ticked:
-> creates backup
-> **changes size by exe by minus 4 KB!!!** WHY?
-> but happens as well with version v2.14! So maybe we should look into that...

- uninstall works fine, but doesnt give any response anymore? Haven't checked any AIV uninstallation yet!!!
-> actually the v2.14 version removed all the original aiv files on uninstall and restored no backups, so this is an improved behaviour!!!
- uninstall seems to not give any error if no backup file is found

- now starting to install with just one option ticked at a time, and checking if an error occurs without starting the game yet
- everything installs and uninstalls fine besides the following:
-> **first option to crash is the one with 'nearest enemy. With the top box set, without any subboxes set it works (this shouldn't even be an option?) but with any of the subboxes set, it crashes "object instance missing for objec reference" or sth along those lines.**
-> **subboxes for deactivate demolishing for money of the AI lords also gives same error!!**
- subboxes ticked one or both for increase rate of attack troops 8which shouldnt be possible with both) installs fine, but i doubt the effect is what it should be?!
- **Override set-up identity menu does throw error: Label not found! Player color chosen**
- **error for strongholdify with subboxes again, object isntance for object reference missing or sth**
-> but worked with only the lat subbox enabled!
-> also default behaviour for strongholdify, was different in the 2.14 for areason. Don't automatically select all subboxes!

moving on to the AIV installation:
- intalled Tatha castles, it created a backupfolder named: "original" in the aiv folder.
-> clicking install again, it asked:Custom modified AIVs detected. Click 'Yes' to overwrite original backup, 'No' to deleted modified files, 'Cancel' to cancel.
-> Buttons have different names, they seem to be set by OS language default which is pretty stupid, they should instead be set by the language setting of the UCP!
-> cancel works as intended
-> yes does overwrite the original backup?! Why? That makes no sense, i would want to keep the original and create another backup, if anything!
-> also this seemed to be triggered, as the checksum of all files was taken, and it seemed like the installation didn't actually swipe out all the original files. As Tathas castles don't contain the Wolf5E catle, which is part of the original aiv folder.
-> **Thats is important. If aiv files get installed, all files of the original folder should be swiped and put in the backup folder!**
-> somehow tho, when the programm detected that the original backup exists, this process works, and all files are removed, even the one with the name Wolf5E.aiv
-> what does button 'no' do? If you click it, why don't i get the option to backup my custom castles? The dialog just doesn't make sense right now!

-> uninstall did just resurrect whatever was inside the 'original' folder and wiped out the rest.

summing up the experience, the new aiv installation just is worse than the old one and even worse than the one found in prior to v2.14 unfortuantely, because of the missleading dialog box. but i hope this gets improved upon, as it has huge potential. I would also like to see this get the same behaviour of installing partial aiv's with the 'overwrite' option or something, mainly giving the installign person the possiblities to:
-> multiselect
-> select an option if all castles should be removed before installation of the new ones, or if just existing ones get overwritten, and the rest stays the same.

moving on to the AIC section.
- installing and uninstalling went smooth, didn't test effect
- also installation with multiselect possible, but didn't test effects.
- **it seems like something in the AIV section broke. Even tho all boxes were unticked, it still showed me the dialog that it had backups of aiv's and wanted to overwrite some originals. THIS SHOULD NOT HAPPEN!**
- openeing the prefs.json didn't reveal anything unfortuantely, like there could have been something like an aiv config? There was definitly a 'hash' but it should be something else? Unless the 'aiv-hash' was saved under just the name 'hash'
-> removing the 'hash' thingy, still didn't resolve the issue and the patcher kept on overwriting AIV files with no aiv boxes ticked and just aic's getting installed!
 

Starttroops and StartResources installation went smooth, but didn't test the outcome.

I guess this gives you now enough stuff to work on @patel-nikhil  :D
Hope i didn't ruin your day with my tests. Seeningthe functionalities tho looked good and the idea behind it is also good. Just the functionality right now isn't there.

Sorry for all the writing mistakes, i have no preview option here, and the spellchecker seems to not know english language.

I ll do more testing in teh future but i feel like a bit exhausted for now ^^

**Comment by patel-nikhil** [comment]
Answering questions first:

> also, only One of the executeables (extreme and normal Crusader) were required to make the OK button come up?
Yes, this is how the UCP currently works as well.

> also now has my v1.1 version safed, how do i get it out of there? Need to open pref
As it should be since there is a dropdown to select path. The goal here is to make path selection easier - for the select few that have multiple installs, we can reasonably expect them to know where they have installed each to. Selecting a path using the dropdown shows the full path so there can be no confusion where you are installing to.

> it also doesn't remember any optiosn ticked, if closed completely and opened again, the config just straight up seems to not work at this point
There is an option to disable/enable 'autosave' in the preferences file. Default I had put as false so that you don't have to worry about accidentally losing a config by clicking a box here and there. But true may be the better choice being consistent with past implementation.

> selecting deactivate demolishing for money of AI lords does now autoselect all 3 options
This is better design, in my opinion because in a hierarchy you expect the 'main' option to include all 'suboptions' when you select them. In terms of the changes it makes to the game, maybe not. This should be able to be modified to match the previous default.

>  clicking install again, it asked:Custom modified AIVs detected. Click 'Yes' to overwrite original backup, 'No' to deleted modified files, 'Cancel' to cancel.
> > yes does overwrite the original backup?!
I do not see why this is surprising

> ... it seemed like the installation didn't actually swipe out all the original files. As Tathas castles don't contain the Wolf5E catle, which is part of the original aiv folder...
I'll look into this, but when clearing the 'original' folder it's possible it may only erase .aiv files

> what does button 'no' do? If you click it, why don't i get the option to backup my custom castles? The dialog just doesn't make sense right now!
I'll revisit and revise this

> I would also like to see this get the same behaviour of installing partial aiv's with the 'overwrite' option or something
AIV multiselection does not make sense without being to preview castles in my opinion. At best it could be implemented akin to the proposed upgrade to AIC multiselection.

> it seems like something in the AIV section broke. Even tho all boxes were unticked, it still showed me the dialog that it had backups of aiv's and wanted to overwrite some originals. THIS SHOULD NOT HAPPEN!
Now this is curious.

> There was definitly a 'hash' but it should be something else
The hash in the preferences file is only used when resolving the installation path. For AIV files a hash of the files is taken and used internally to determine how to handle installation.

> AIV sets have no description? Seems like the localization linking broken there
They were hardcoded in the localization files before. I've modified that to load them from a json file but have not copied the strings over yet.

> installing with no boxes ticked:
> -> creates backup
> -> changes size by exe by minus 4 KB!!! WHY?
> -> but happens as well with version v2.14! So maybe we should look into that...
- The extra backup can probably be fixed.
- Behaviour with no boxes should probably be fixed.
- With some boxes ticked the exe size will be different from v2.14 because for some changes such as AIC 2.14 and previous versions installed a dummy change for this if none was selected.

**Comment by patel-nikhil** [comment]
Issues to be fixed:
- [ ] Uninstall (with and without .ucp_backup present) gives no user feedback
- [ ] Save config dialog should have file filter applied
- [ ] Save config causes crash
- [ ] Loading a broken config updates the mostRecentConfiguration
- [ ] Cancel button should close the program
- [ ] Autosave option should default to true
- [ ] Add margins and background colour to description text
- [ ] `Deactivate demolishing for money of AI lords` option should only select first option when clicking the main checkbox
- [ ] `Increase Rate of attacktroops` options should be mutually exclusive
- [ ] Consider adding progress bar?
- [ ] Unchecking `colour change` option should revert image to colour red
- [ ] AIV description needs to be updated in the JSON
- [ ] AIC multiselection prompt missing
- [ ] AIC export missing
- [ ] AIC refresh missing
- [ ] `AI attack target` change causes crash
- [ ] `AI attack target` change is selectable without selecting subchange
- [ ] `Deactivate demolishing for money of the AI lords` causes crash
- [ ] `Override set-up identity menu` throws error: the label is not initialized
- [ ] Issue with `Strongholdify` changes
- [ ] For AIV installation prompt `No` should trigger savefiledialog
- [ ] All change configurations should be disabled after installing and when not selected

**Comment by GRhin** [comment]
Sorry to come so late to the party, but as long as we are revamping the UI, how hard would it be to update the design too?
image
This is a quick mockup idea i came up with. All graphics come from the game.
There is a clear difference from checboxes to radio buttons. 
The descriptions are split out from the suboptions and are found on the ? buttons, and the > buttons indicates that a feature has suboptions available. 
The maximise icon is probably not needed/wanted, the current version has a ? there. Could replace some of these with other game graphics.

**Comment by patel-nikhil** [comment]
- Not sure if SHC graphics can be used in the UCP, may need to check with Firefly/fair usage (legality)/Sh0wdown (repository owner)
- In C# (WPF) I am not the best positioned to provide an accurate estimate of the feasibility and effort required, however with a finalized set of mocks I would say:
 - ~1 week for headers, background, button, and the menu. 
 - Unknown feasibility for styling of the inside of the progressbar using image background. But minimal effort for the progressbar background.
 - Updating individual options: ~1.5 weeks, depends on mocks
 - Testing and bugfixing: 1 week

All of the above estimates are dependent on this PR already being merged, and are based on ~3 hours of developer work per day.

**Comment by GRhin** [comment]
The ucp already uses shc graphics for its ui. So this will not make that any worse.

**Comment by patel-nikhil** [comment]
> The ucp already uses shc graphics for its ui. So this will not make that any worse.

I never actually noticed or made the connection &#128514;
So the first point from my list is moot. Meaning it comes down to having mocks that the project managers approve of, and then of course, dev work.

**Comment by Krarilotus** [comment]
I definitely would think, that a UI overhaul would be needed in order to make this change we have here, also a good change for the end user. Right now, the new skin has the same looks with somehow less functionality. Ofc. this will change, and it will change a lot of things in the backend. I doubt though, that any end user would be pleased with a push of the GUI as it is now, just because they dont see a benefit for them.

GRhin's design idea looks very good in my eyes. I would prefer to discuss it with the rest of the team first and see if anyone would want to put in the hours for it! It is kinda what people are hoping for i would guess, when they hear 'New GUI!' ^^

**Comment by Krarilotus** [comment]
This will be revisited after the next release!

**Pull request closed without merging**
