### PR TITLE
Added apple orchard build size fix

### PR DESCRIPTION
**Pull request by LordHansCapon**
Fixes the apple orchard's placement size. Placement size was 1x1 tile bigger than the built building size.

**Before:**
before

**After:**
after

**Test build:**
https://we.tl/t-2tBzGEhvub

### CODE REVIEW

**Comment by Krarilotus** [comment]
i would actually argue, the plöacement size is the right one, and the buildign size is the wrong one
The placement size enabled you to build farms on less fertile land than the cheese farms btw.

**Comment by LordHansCapon** [comment]
Thats an unintended side effect. Will be revised.

**Comment by GRhin** [comment]
I would argue that the placement size indirectly nerfs cheese farms which are weak enough already. So I have no problem making the apple and cheese equal in this regard if that's what you are saying. An argument could be made for giving map creators more options, however aside from those options I dont think it matters which way you do it from a balance standpoint.

**Comment by Truetobi91** [comment]
I found another bug regarding orchards:
#682

**Comment by LordHansCapon** [comment]
> I found another bug regarding orchards:
> #682

Unrelated to this issue, but fixed it in a new PR: #684

**Comment by J-T-de** [comment]
Yeah, I also think the placement size is the right one, at least it is like this in Stronghold and the AIV Editor. Also, it makes for me more sense to have `tree_size (=3)  + path (=1) + tree_size (=3) + path(=1) + tree_size (=3) = 11 tiles`...

**Comment by Krarilotus** [comment]
Its far  more difficult to change the placement size it seems. But for now, this is better than nothing. We should revisit this change tho in a later version!

**Comment by Truetobi91** [comment]
I found a bug with the current fix. I'd say the fix only focuses on the building size but not the deletion size.

If you have a 10x10 orchard directly adjacent to any other farm on one of the two sides where the 11th lines was removed, it causes a small bug when that orchard is being destroyed or deleted. The bug is that this 11th line of tiles causes unbuild tiles on the adjacent farm to become buildable even though they are IN the building frame of that farm. It does not remove anything from the farm e.g. the fences of the dairy farm ot that hops trellis for hops farms. You could e.g. build a wall in the fence gaps of a dairy farm. The bug is 100% reproducible and let's you manipulate other farms actively.

**Comment by Truetobi91** [comment]
OK I need to clarify that this is a vanilla bug. It's not caused by your fix!

**Comment by Krarilotus** [comment]
@Heroesflorian is this possibly a SHC magic eraser? :D

**Pull request merged**
