### PR TITLE
Command line interface for UCP

### PR DESCRIPTION
**Pull request by patel-nikhil**
The following changes allow for a silent/automated installation of the Unofficial Crusader Patch as well as allowing command-line arguments to facilitate easy installation of aiv, aic and map files.

Motivation:
This allows for easy setup for multiplayer when trying to share configurations, as normally you would have to manually copy of aiv, aic, and map files. Additionally when sharing configurations by default you need to either share ucp.cfg file or manually select options. With the CLI build you can just put the UCP install in the installation folder or a subfolder and it will install based on the ucp.cfg

Reference issue with original request: #479 created by @GRhin

Old behaviour:
Download UCP, double click UnofficialCrusaderPatch.exe and click through install

New behaviour:
Unofficial Crusader Patch builds as a library (dll), and the GUIand Console 'versions' are built separately on top of that. Installation will require the dll and the executable.

GUI: Download release, extract, double click UnofficialCrusaderPatch.exe and continue with install

CLI: Download release, extract, double click UnofficialCrusaderPatchCLI.exe and install will proceed (no GUI)
For advanced users or custom setup: Run via command-line. (Optional) Pass arguments to the executable. Installation will proceed. Upon completion, command prompt will display the following message: 
<br>
`UCP successfully installed`<br>`Path to Stronghold Crusader is:<Path>`

Optional command line arguments are as follows:
`--aiv[-overwrite]=<relative path to source aiv folder>`
`--aic[-overwrite]=<relative path to source aiv folder>`
`--maps[-overwrite]=<relative path to source maps folder>`
`--mapsExtreme[-overwrite]=<relative path to source mapsExtreme folder>`
`--no-output`

Enclosure in square brackets indicate optional presence.

Behaviour is as follows:

Default mode is copy. I will use aic files as an example.

Output:
- When the CLI tool is passed an argument it will by default display where files, if any, are saved to. It will also display what files (ie. aic) are copied, and to where (see below for details). This feature can be disabled by running the CLI tool with the argument `--no-output`

With argument `--aic=<aic path>` the following happens:
- Files in "aic" folder of installation are copied to folder bak-YYYY-MM-DDTHHMMSS
- Files from \<aic path> folder are copied to aic folder of installation 
- Installation proceeds. The files copied from <aic path> can be used for install so long as they are specified in the ucp.cfg

With argument `--aic-overwrite=<aic path>` the following happens:
- If file with filename 1.aic exists in "aic" folder of installation and <aic path>
 - file 1.aic is deleted
 - new 1.aic is copied from \<aic path> to "aic" folder of installation
 - Installation proceeds. The files copied from \<aic path> can be used for install so long as they are specified in the ucp.cfg

### CODE REVIEW

**Comment by ByBurton** [comment]
I'm not gonna merge this right now. I kinda want to know what @Sh0wdown thinks about this.

**Comment by patel-nikhil** [comment]
Thanks, yeah this is something I believe will be very useful and will make using UCP a lot easier for a lot of people :)

**Comment by ByBurton** [comment]
@patel-nikhil Welcome in our team btw. 👍 
We will be making a lot of changes in the nearer future so we can more easily chat and develop the UCP together.
I'm working on a discord, and we will create a 2nd branch (develop) so the latest untested changes are not on the master.

**Comment by GRhin** [comment]
Can I just point out another application of these changes? - this will allow modders to release there own mods with 1-step install. 
You want Krarilotus's 4-char castle? download a zip with a .bat file that installs castles, maps, aic, and patcher.
You want ByBurton's custom AIs? download a zip with a .bat file that installs castles, maps, aic, and patcher.
Krarilotus's christmas campaign? download a zip with a .bat file that installs castles, maps, aic, and patcher.
This would be much easier for new modders to share their work independantly.

**Pull request merged**
