### PR TITLE
Added stop player keep rotation change (created by gynt)

### PR DESCRIPTION
**Pull request by LordHansCapon**
Player castles now keep the original rotation set in the editor.

**Creator: @gynt** 

**Test build:**
https://we.tl/t-y7fBGPoH0q

### CODE REVIEW

**Comment by Krarilotus** [comment]
i tested it with crusader and extreme, and it rotates the keep as expected for the player, but the description is wrong.

The description should be:
caption: rotate player keeps
description: player keeps now get rotatedthe same way, that AI keeps rotate on a map, facing with their campfire outwards towards the map edge.

i also tested loading games wihtout the change, and the keep is fine as it was. This now makes possible to make players start with custom keep rotations somewhat even in saved games to maps 👍

**Comment by Krarilotus** [comment]
this is awesome, also tested with other game settings and maps, and this works throughout the entire stack!

**Comment by Krarilotus** [comment]
ok i can just change the description myself 🗡️

**Comment by Truetobi91** [comment]
The fix does not change the rotation of recruitment buildings aka barracks, mercenary post, engineer's guild and tunneler's guild which feels awkward when rotating the map to the degree that shows the keep in the standard fashion.

**Pull request merged**
