### PR TITLE
Added option to customize starting resources

### PR DESCRIPTION
**Pull request by patel-nikhil**
The change is as depicted in the picture below.
It will load json files that contain the configuration from subfolder resource/json and will change the starting resource values (including gold) for each game mode.

Gold is specified based on fairness: (adv = advantage)
[large human adv, slight human adv, no adv, slight ai adv, large ai adv]

image

```{
	"description": {
		"English"	: "My custom resource file",
		"German"	: "My custom german resource file",
		"Russian"	: "My custom russian resource file",
		"Polish"	: "My custom polish resource file",
		"Chinese"	: "My custom chinee resource file"
	},
	"normal": {
		"gold": {
			"human": [4000, 3000, 1000, 500, 250],
			"ai": [2000, 5000, 6000, 8000, 10000]
		},
		"wood": 500,
		"hop": 5,
		"stone": 2,
		"iron": 3,
		"pitch": 4,
		"wheat": 5,
		"bread": 6,
		"cheese": 7,
		"meat": 8,
		"fruit": 9,
		"beer": 10,
		"flour": 11,
		"bows": 12,
		"crossbows": 13,
		"spears": 14,
		"pikes": 15,
		"maces": 16,
		"swords": 17,
		"leatherarmor": 18,
		"metalarmor": 1
	},
	"crusader": {
		"gold": {
			"human": [8001, 4001, 2001, 1001, 501],
			"ai": [4001, 6001, 8001, 10001, 12001]
		},
		"wood": 10,
		"hop": 5,
		"stone": 16,
		"iron": 15,
		"pitch": 14,
		"wheat": 13,
		"bread": 12,
		"cheese": 11,
		"meat": 10,
		"fruit": 9,
		"beer": 8,
		"flour": 7,
		"bows": 6,
		"crossbows": 5,
		"spears": 4,
		"pikes": 3,
		"maces": 2,
		"swords": 1,
		"leatherarmor": 20,
		"metalarmor": 21
	},
	"deathmatch": {
		"gold": {
			"human": [8002, 7002, 6002, 5002, 4002],
			"ai": [3002, 6002, 12002, 24002, 48002]
		},
		"wood": 15,
		"hop": 5,
		"stone": 10,
		"iron": 17,
		"pitch": 6,
		"wheat": 5,
		"bread": 2,
		"cheese": 19,
		"meat": 24,
		"fruit": 10,
		"beer": 8,
		"flour": 1,
		"bows": 2,
		"crossbows": 3,
		"spears": 100,
		"pikes": 204,
		"maces": 79,
		"swords": 21,
		"leatherarmor": 1560,
		"metalarmor": 13
	}
}

### CODE REVIEW

**Comment by GRhin** [comment]
Very quick testing, Works, and works in multiplayer.
The file is not accepted if you do not specify a gamemode. I would like to only modify "Deathmatch" or "crusader" and leave "normal" as vanilla, to do that I will need to enter vanilla options into the startres.json - can you change this so if i dont specify a gamemode it leaves that mode as default?

**Comment by Lolasik011** [comment]
@patel-nikhil Can you share the last build ?

**Comment by GRhin** [comment]
Are you on discord? It was shared in the testers channel.
 I think there is a fair bit of stuff from this and other new features with
translations needed...

**Comment by Lolasik011** [comment]
> Are you on discord? It was shared in the testers channel. I think there is a fair bit of stuff from this and other new features with translations needed...

How do I get into the testers channel?

**Comment by Krarilotus** [comment]
We did test this on GRhins stream today, where this setting now worked without bugs. You still need to install the patcher with the same settings for multiplayer to make them compatible.
I would love to know if someone has made a test for faulty jsons?
will test that now!

**Pull request merged**
