### PR TITLE
Added apple farm block fix.

### PR DESCRIPTION
**Pull request by LordHansCapon**
Fixes apple farmer blocking issue, where placing any solid non-walkable building or terrain at the top left of the apple farm would bug out the farmer and he would not do his job unless there is another apple farm on the map.

grafik

See #682 

_Fixed by moving the first destination of the apple farmer inside the farm, so it is no longer blockable._

**Test build:**
https://we.tl/t-2KMVkYZOak

### CODE REVIEW

**Comment by Monsterfisch** [comment]
it has been mentioned before but i think it worth pointing out again just to make sure.
the apple orchard should be larger in size so it resembles the preview of the farm due to the smaller final farm it makes it so that you get situations where you cant replace a destroyed apple farm because you have placed buildings on the area that is required in the preview.  as seen here 

the reason, why i would say bring back the original size, is to balance out the farm in terms of cost to production by making it more space demanding

**Comment by GRhin** [comment]
I believe that's in another pr

**Comment by Monsterfisch** [comment]
ah yeah you are right my bad

**Comment by Heroesflorian** [comment]
@LordHansCapon as a side note, this approach to fixing the problem (i.e. just simply moving the first location to a different single tile) does not prevent the issue in 100% of cases. 

To illustrate why that is the case, this is a screenshot from a quick example in the map editor: 
grafik
One can place terrain with different height, as well as rocks and water inside an apple orchard. 
This apple orchard still has a number of perfectly accessible apple trees, but depending on where those rocks / water / inaccessible elevated areas are, any single hard-coded tile can be obstructed. 
If the apple farm is then idle, it is not really obvious to the player why that is (at least for less extreme examples). 

Note that I do not say this would be an issue (as at map design time you can avoid it if you know the particular tile, and ingame you cannot place rocks and stuff), but... yeah, just wanted to mention it for the sake of completeness.

**Comment by LordHansCapon** [comment]
@Heroesflorian Yes of course it does not fix the problem for all use cases. But it fixes the most common issue which occures like 99.999999999999999999999999% of the time rather than the one you just mentioned, which is enough.

**Comment by Heroesflorian** [comment]
Yep, didn't mean to state anything else.

**Comment by Krarilotus** [comment]
Do you have a current testbuild? Could you instead of using wechat just use google drive where it doesn't expire?

**Comment by Krarilotus** [comment]
tested both with SHC and SHC-E, farm worker behaviour remains besides the different first step unchanged. They still collect apples from nearby farms and do other bitsa and pieces that apple orchard workrs do. They even collect through blocking walls fromthe right and left bottom side (where the buildsize is shrunk a bit after palcement)

**Pull request merged**
