### PR TITLE
Added spearmen run change.

### PR DESCRIPTION
**Pull request by LordHansCapon**
Added an option to make spearmen run by default instead of walking.

**Test build:**
https://we.tl/t-ZMb1UJmrJ5

### CODE REVIEW

**Comment by F2eRNI8** [comment]
Tested with both vanilla and modified AIs, as well as played a few games to see if it works with other game features. So far I haven't found any bugs or other issues - approved by me.

**Comment by ByBurton** [comment]
Have tested it with regular Crusader and the extreme version and haven't found any bugs.
I tested with all the vanilla AIs in like ~12 games. I think this is fine.

**Comment by Krarilotus** [comment]
@LordHansCapon can you provide pls the full file set or is there no changes in the changes.cs?

**Comment by LeSpec** [comment]
Instead of setting that memory to the value 2, it's sufficient to remove the jump if equal at 0055E07E.
"That memory" has something to do with auto attack / aggressive stance. It switches from 0 to 2 if enemies are in range.
I hope this fixes it. (Rat's AI patrolling works in 1.41)

**Comment by StrongholdFun** [comment]
Vocabulary used in this post:

Arrow Defense/AD= the number of arrows a unit can take until they die
UCP = UnofficialCrusaderPatch
Poleturners = spear/pikemakers
Micro = Micro-Manage, the the action of personally controlling units and clicking rapidly to dodge melee or ranged attacks or concentrate ur own attacks 

Note: Vocabulary is not ordered alphabetically, but in order of most important to least important.




For all of you against a major buff to spearmen and monks speed please read this: If you have ever watched any competitive stronghold crusader tournaments online you will notice 1 thing, all competitive players always spam horse archers and portable shields together with assassins and then later go for pikemen and knights, siege engines aside, for both defense and offensive situations only these five units are used* I will repeat again horse archers, portable shields, assassins, pikemen and knights. For ur casual games against AI's it may seem like the spearmen with the 5 arrows to die buff and monks that are killed by only 4 arrows (yes it only takes 4 arrows to kill a monk even in the UCP) are worth building, they are not for competitive games using the UCP spearmen are never used, in fact even in semi competitive matches the winner of the match never builds any spearmen or monks, they can't afford to.

This isn't just my opinion this is is mathematical fact, in the UCP a spearman takes arrows to kill, while a maceman takes 15 and a pikeman takes 50 arrows to kill according to the http://stronghold.heavengames.com/gameinfo/tables/melee which editor testing in the UCP can confirm is still the case, now a pikeman costs 20 gold+1 pike(1 wood=5 gold for sell price)+1 armor(1 iron=around 25 gold sell price) so if the map is a standard map with the materials to gather these materials a pikemans total material cost is 30 gold+probably around 5 gold for the food costs of the armorer and the poleturners workshops being populated, so that means its around 35 gold total production cost for a pikeman, while a monks total production cost is 10 once ur past the 1K cost of the cathedral however it only takes 4 arrows to kill that monk while it takes 50 to kill a pikeman.

This means even as a defensive unit that is more than 3x cheaper the monk is still not worth production. for one you can only recruit units as fast as you can gather population around ur campfire this means that you can only recruit around 2.5 units a second even with gamespeed at 90 so even assuming its a small map and you already planned to have a cathedral those 3.5 monks per pikeman cost doesn't make sense to buy them. because 3.5 monks have a health of 4*3.5 which is 14 arrow shots you can take vs 50 for the single pikeman you can buy for that price, that's around 4x less ranged defense for the 3.5 monks you bought vs that pikeman. 

In real games where the opponent is a person and they can spam then micro horse archers or normal archers the monks will get cut down by volleys of arrows before they can reach them, and if the monks stay behind the walls like many of you claim is there useful purpose then the horse archers will do continuous volleys of arrows killing all the defending monks quickly and brutally as they pin themselves behind the walls. many of you might respond saying the archers on your own walls would be able to defend them, but it is simply not the true or players would use monks to defend their castles in competitive matches which I will link to some random ones below*

https://www.youtube.com/watch?v=MEBUIYsyu18
https://www.youtube.com/watch?v=M1uEQRyalhQ

Please if any of you actually think that monks can be used competitively for defense please link me a youtube videos of a tournament where the winner of the match builds atleast 20 monks.

The takeaway? The developers of the UCP or someone atleast needs to atleast add the option to give a massive buff to monks and spearman, the buff being a mix of speed and arrow defense, (in my opinion the spearman should get more run speed while the monks get more health for the balance)

I think the Monks should have there arrow defense buffed from 4 to atleast 10 and have a charging radius like macemen in the original stronghold while spearman should have there arrow defense buffed from the current 5 to 8 and always run, if they don't always run they should have a AD of 12 reflecting the fact that their slowness is because their cloths is stuffed with straw/wheat which actually would defend better against arrows than leather armor if they had enough it would slow them.

Thank you for reading if you have any ideas to add to my post or evidence for ur point, feel free to reply.

**Comment by GRhin** [comment]
I can destroy your long argument very quickly. If you change the balance, then every argument about multiplayer is no longer valid, and needs to be reconstructed based on new info. The fact of the matter is, other units are the cause of the current situation you describe, rebalancing them will change the importance of monks and spears as well. Add to that the fact that the multiplayer games you are referring to use maps that are specifically designed to make the most of the shield/horse archer strengths, which means the maps themselves nerf the units that are weak to horse archers.
Your values for pikes are well off, as you assume that the cost of the weapons is only the food for worker, plus the cost of the raw materials. This is a way of looking at it, but it misrepresents the true value. Personally I use the sell value of the weapon. For metal armour, it is considered a good profitable economy to make and sell, so your cost is not selling them to pay for other units. Pikes is less obvious, as the alternative to using pikes is not necessarily selling them, you might instead be making spears for sale or building flecthers to sell xbow, but sell price of the pike I believe to be more accurate.
Next you spent a bunch of time talking about the arrow resistance of monks and spears, but you completely ignore the reality that there is usually horse archers and shields there to take the fire instead of these units. Or the monks could sit behind the shields and completely invalidate that argument. Then be used to fight or keep off enemy pikes or knights.
I can find you a video of monks being super important in multiplayer, however it is in bootstrap style, which I figure you might decide isnt valid because it's not ththe same as what you are experienced with. Let me know if my providing that will be usefull to you.
The reason the example is in a bootstrap game, not your regular multiplayer , is that in a bootstrap game gold value is important, as you slowly build up armies and eco. While in a peacetime game, you get to skip all the intermediate steps where gold value is important, and jump to the end game where the most important value is power per unit, and concentrating that strength. When you skip steps, units that are strong in those steps will seem underpowered.
Having said all that, I am not arguing against the change you have commented on. Spearmen running I have no problem with, I dont think it's really needed, but I do recognize that spears are pretty weak at the moment.
If you want a more in depth discussion of unit balance, hit me up on discord. I'm in the ucp server so it should be easy to find me.

**Comment by GRhin** [comment]
> now a pikeman costs 20 gold+1 pike(1 wood=5 gold for sell price)+1 armor(1 iron=around 25 gold sell price) so if the map is a standard map with the materials to gather these materials a pikemans total material cost is 30 gold+probably around 5 gold for the food costs of the armorer and the poleturners workshops being populated, so that means its around 35 gold total production cost for a pikeman

Sorry this section confused me, causing edits in my last response. Either way, your result is wrong.
20+1(wood sell value)+21(iron sell value) +5(your assumed food sold value) = 47 not 35. making nearly 5x the cost of a monk, not the 3 you used. In the last message I used a different calculation, which i believe to be more accurate, giving 7x the cost (68 gold).

> it only takes 4 arrows to kill that monk while it takes 50 to kill a pikeman.
I am looking at the stats right now, and its actually only 3 arrows to kill the monk. However, you are still comparing the monks weakness to the pikemans strength, which is misrepresenting the comparison between the units, at best.

Again I am happy to discuss in more detail. But know that I will require the whole situation to be considered, not just the current multiplayer balance, maps, and rulesets, which specifically force the monks weakness to become more of an issue. 
If you check my name on YouTube, you will see my "bootstrap" games, with good players, there are videos with lord burek, medamri, and mystical, showing that the lesser known regular players arent bad players making bad strategies that work because their opponent doesnt punish it. 
The "bootstrap" games have no peacetime and no start gold - this means that early game they are forced to use units that are cheap to be able to fight off their opponent, starting often with primarily slaves, slingers and assassins. Slowly moving into Horse archers and shields. The maps are alot more dynamic, with hills, cliffs, and extra resources outside of build range, forcing players to split armies up, to protect/attack multiple areas at once.  With this setup, it almost seems like a different balance is being used already just looking at the games, but its just map and start conditions different. 
Even here monks arent usually very good, more due to the investment of the cathedral than anything else. when you have low gold, spending 1000 gold at once on a building isnt attractive. however, the times that the monks have proven their value is when their is a large assassin raid, 2k gold spent on a cathedral and monks will kill more than 2k gold worth of assassins. once the cathedral is built, the player has a large advantage with the monks from that point on untill the opponent gets his own cathedral.

My recommended rebalance starts with the shields, make them slower, about the speed of pikemen, crossbows and monks, and with that one change, the monks stay with the shields, and you use enough of them to justify the cathedral in most games, making the monks now much better than the pikemen whose strength is surviving without the sheilds.

**Comment by LeSpec** [comment]
"I can find you a video of monks being super important in multiplayer, it is in bootstrap style" - GRhin
I'm interested.
How about adding monks to churches for a test?

**Comment by GRhin** [comment]
I'll find it tomorrow.
The problem with adding them to churches is that it reduces the point of getting a cathedral. 
Furthermore, I believe with the slower shields the monks are actually valuable enough to justify the cathedral fairly early, and saw them way more often in my testing of it.

**Comment by LeSpec** [comment]
Nvm, i played some matches with Altaruss today and i agree, monks are pretty good already even with the 1k for the cathedral.

**Comment by GRhin** [comment]
Yea, once you have monks, they can be pretty scary, basically you can out melee your opponent all day, and it quickly pays off. As long as you can keep arrows off of them.
The problem is justifying 1k gold at once for the cathedral. Once paid, you have a huge advantage, but untill then there are often other things to spend the gold on, more shields and horse archers for example

**Pull request merged**
