### PR TITLE
Strongholdify

### PR DESCRIPTION
**Pull request by J-T-de**
Hey guys,
I wanted to share some edits I did together with @Chaf1812. We were not so sure about this, as it was more of an 'educative mod' for us.

We called it Strongholdify, as it adapts (currently 3) game mechanics to match Stronghold 1
1. Reduce Beer Popularity
cuts the popularity bonus from beer by half 
2. Remove cathedral  and church bonuses
removes church, cathedral and (church and cathedral) bonuses
3. Reduce Resource Quantity
removes skirmish mode's +50% resource bonus

These changes are very questionable, as it renders some AI in skirmish mode useless. However, there might be some use in custom scenarios or multiplayer wit Stronghold rules ;)

(Using Visual Studio 16, I was not able to not commit the change in the UnofficialCrusaderPatch.sln, switching from Visual Studio 15 to 16...)

### CODE REVIEW

**Comment by LordHansCapon** [comment]
Interesting, but it has more use in Multiplayer because as you said yourself it renders some AI pretty useless. Caliph for instance depends on his Ale and taxation. Lionheart and many other use churches to gain popularity and tax people aswell.

**Comment by GRhin** [comment]
Not nessacarily,  someone could write an aic file to work with this balance, however those edits were made for a reason, the ai will never be as good with the resource "bonus" removed. Crusader generally has less resources, especially farm space, so you gave a weaker economy, that is why the "bonus" was introduced.
I'm not sure this is worth it for multiplayer however as if you want to play stronghold rules you can just play stronghold multiplayer.
As for custom scenarios, they already use the stronghold rules already unless you use the sav to map trick. However the different popularity options might be useful to somebody.

**Comment by J-T-de** [comment]
> someone could write an aic file to work with this balance

could, but I think nobody is interested in creating a niche aic for a niche edit... except, maybe, Stronghold Europe rises from the dead...

> However the different popularity options might be useful to somebody.

this is why we set it up for discussion and not just let it die on our PC :)

**Comment by ByBurton** [comment]
This sounds very interesting, kinda like it!!!

**Comment by ByBurton** [comment]
Question: Does it also decrease the bonus speed for peasants to spawn?

**Comment by J-T-de** [comment]
> Question: Does it also decrease the bonus speed for peasants to spawn?

Not yet, but I think I already found the function.

> Not working btw.
> image

I checked 1.4.1, 1.4.1-E and 1.3(.0) for skirmish and free build before I pushed. Is this scenario or spectator mode? I will check tomorrow.

**Comment by J-T-de** [comment]
Okay, something is wrong. All 3 different options should be toggleable...

**Comment by ByBurton** [comment]
I am watching an ai play in spectator mode.

**Comment by J-T-de** [comment]
Okay, somehow some parts of the Version.cs edits are not there... Please don't ask me, why... I will fix this ASAP.

**Comment by J-T-de** [comment]
@ByBurton added the missing parts, works now for me again. Sorry for the mistake on my side...

**Comment by ByBurton** [comment]
Thank you, working now :)

**Comment by ByBurton** [comment]
@J-T-de did you find something for the peasant spawning?

**Comment by ByBurton** [comment]
@J-T-de I'm gonna close this issue. If you have future plans / issues please open up a new one. I love you for this.

**Comment by Krosstack** [comment]
@J-T-de How can one increase peasant spawnrate even more than in vanilla gameplay? I can see that Strongholdify decreases it and I want to increase it.

**Comment by GRhin** [comment]
It is not currently implemented, though I imagine that it would be easy to do as strongholdify already changes the rate, someone just needs to cook that code and change the direction.

**Comment by J-T-de** [comment]
I will take a look into it, because this was asked often now.
My implementation did not change the respawn timer, but suggested the game that we are currently in is Non-Skirmish (like Castle Builder), so this is a dead end... But iirc, there might be a timer somewhere in the vicinity, so this could work.

**Pull request merged**
