### PR TITLE
factor out extra defense

### PR DESCRIPTION
**Pull request by J-T-de**
As requested, I factored out the extra defense probability. But i feel this needs more discussion
- this option is currently *deactivated* by default
- I need to refine the phrasing depending on the discussion

I feel this option should get removed completely. I see the historical necessity (no aic), but now it is not needed anymore, and finetuning aic gets harder. Options:

- keep it forever
- keep it checked for the next release, for the one after unchecked, and for the one thereafter completely remove it
- remove it, put in the patchnotes and see what happens

I think the second option is the best balance between usability for content creators and users, and we depricate this feature over time.

### CODE REVIEW

**Comment by ByBurton** [comment]
> As requested, I factored out the extra defense probability. But i feel this needs more discussion

Does this mean you only removed the extra probablity that was added to each and every AI?

**Comment by gynt** [comment]
@J-T-de I think we should rip off the bandaid quickly instead of slowly. 
I am in favour of making the option deactivated by default, and add a DEPRECATED description to it. Remove it completely in the next feature. The reason for keeping it in for now is that people can verify themselves that the deprecation of this option caused their AI to behave differently (and can adjust accordingly themselves).

**Comment by J-T-de** [comment]
> 
> 
> > As requested, I factored out the extra defense probability. But i feel this needs more discussion
> 
> Does this mean you only removed the extra probablity that was added to each and every AI?

Yes, I added an extra sub-option to toggle the flat bonus legacy feature.

> 
> 
> @J-T-de I think we should rip off the bandaid quickly instead of slowly.
> I am in favour of making the option deactivated by default, and add a DEPRECATED description to it. Remove it completely in the next feature. The reason for keeping it in for now is that people can verify themselves that the deprecation of this option caused their AI to behave differently (and can adjust accordingly themselves).

From the developer side, I agree, but I don't know how it will influence the user and content creator side...

**Comment by J-T-de** [comment]
As discussed on discord, we fully remove this legacy feature, update the bundled aics to reflect this change, and put a big exclamation mark on the changelog.

**Comment by Krarilotus** [comment]
i ll review code, if it does exactly what i did test already on my local repo i will merge it.

**Pull request merged**
