### PR TITLE
spearmen run change 2.0

### PR DESCRIPTION
**Pull request by LeSpec**
Spearmen also run when selected with archers, kinda inconsistent, but ok i think.

Test build:
https://we.tl/t-37QkGrUk9G

### CODE REVIEW

**Comment by ByBurton** [comment]
And the AI bug was also fixed with this?

**Comment by LeSpec** [comment]
I tested with rat, it rallied spearmen and they were running.

**Comment by J-T-de** [comment]
Discussion: should this option be ticked as standard? I am undecided...

**Comment by GRhin** [comment]
No it should not. 
Basically, the way I see it, if its our opinion that a change improves the game, and an opinion that could be disagreed with (which all balance changes can be disagreed with), then it shouldn't be ticked by default. If a feature objectively improves the game (most bugfixes for example), then it can be ticked by default.
I can imagine someone saying that the spearmen running effects the benefit of other running units like macemen or slaves, and therefore it is not making the game better. 
For myself, I haven't made up my mind on this change, about whether it is better or worse. At this stage ive settled for "its different, not necessarily better or worse". I never really considered it necessary, and dont really see the benefit of it, spears are still easily and cheaply countered.

**Comment by LeSpec** [comment]
Aren't all new options ticked until release, for comfort of possible testers?
It's not compatible with the non modified game therefore it shouldn't imo.

**Comment by ByBurton** [comment]
> I tested with rat, it rallied spearmen and they were running.

"It rallied spearmen" - rally when? For a siege? For a raid?
Or do the defensive spearmen patrol like they should? If so then this seems fine to me, still would need to be tested more.

**Comment by LeSpec** [comment]
Me guessing what rally means, then me using it wrongly. :D
Yeah, i meant patrol.

**Comment by GRhin** [comment]
> Me guessing what rally means, then me using it wrongly. :D

Rally is when you set the location that newly recruited units go by default. It can also refer to the location the AI gathers troops before starting the attack.

**Comment by Krarilotus** [comment]
Anyone actually tested and has a full report of this?

**Review by Krarilotus — COMMENTED** [review]
Files look good

**Comment by Krarilotus** [comment]
Singleplayer tested for patrol for AI, movement for AI, spearmen up and down the hill, through swamp manually controlled, while patroling.

Everything works as expected, same in extreme

**Pull request merged**
