### PR TITLE
Allow overbuilding workers and units.

### PR DESCRIPTION
**Pull request by LordHansCapon**
Allows the player to overbuild workers with buildings, while allowing to overbuild units with walls and towers making them pop at the top.

#595 

**Test build:**
https://we.tl/t-9MVw1TWqqu

### CODE REVIEW

**Comment by Monsterfisch** [comment]
arabian troops cannot be build over with walls/towers, hunterdog/ironminer/healer can not be overbuild.con only be overbuild by towers  you can build over allied peasants (not sure if intended)  for crusader extreme for me

I would also add gates to the overbuilding mechanic for the troops

thats what i got so far

**Comment by LordHansCapon** [comment]
Feature has been updated.

Test build available here:
https://we.tl/t-FBbXldItbd

Zip content:
- UnofficialCrusaderPatch.dll (38 293 504 bytes)
- UnofficialCrusaderPatchGUI.exe (122 368 bytes)

- Gates can now overbuild troops.
- More units are included.
- There is now an owner check.
- Removed unnecessary code.

**Comment by Monsterfisch** [comment]
dont forget to add  hunterdog/ironminer/healer to be overbuildable too =)

**Comment by LordHansCapon** [comment]
Feature has been updated.

Test build available here:
https://we.tl/t-1EqL7y6lPe

Zip content:
- UnofficialCrusaderPatch.dll (38 293 504 bytes)
- UnofficialCrusaderPatchGUI.exe (122 368 bytes)

Changes:
- Added ironminer, healer and hunter dog.

**Comment by Admiral-Gumpert** [comment]
> Feature has been updated.
> 
> Test build available here:
> https://we.tl/t-1EqL7y6lPe
> 
> Zip content:
> 
> * UnofficialCrusaderPatch.dll (38 293 504 bytes)
> * UnofficialCrusaderPatchGUI.exe (122 368 bytes)
> 
> Changes:
> 
> * Added ironminer, healer and hunter dog.

The link has expired , Can you kindly re upload it , or send another link?
Sorry I know I'm kind of late

**Comment by LordHansCapon** [comment]
https://we.tl/t-nB1LzWBIhG

**Comment by J-T-de** [comment]
Not tested thoroughly, but no bugs encountered.

I am no map/scenario creator and I don't care about, but it might be a comfort feature to be able to also overbuild enemies in the map editor. I think one would not need to differentiate between skirmish/castle builder/map editor, as there are enemies nearby would prevent overbuilding enemies strategically in skirmish matches...

**Comment by GRhin** [comment]
Have camels been included?

**Comment by Russianstory** [comment]
@LordHansCapon Are you the author and developer of this mod?

**Comment by GRhin** [comment]
This mod is open source, we invite any and all developers to join in. LordHansCapon is one of the currently active developers.
The original developer and creator is sh0wdown (you can see his name in the github project title and url), but he isnt actively developing at this time.

**Comment by Russianstory** [comment]
OK got it!
I just would like to see the one who makes this particular mod.
It will be great if buildings can be placed on top of ruins and trees, but we have already talked about animals ... camels, dogs, deer and rabbits ...

**Comment by GRhin** [comment]
Oh you mean who made this feature for testing? Yes that is HansCapon.
Overbuilding ruins probably wont be popular, as map creators sometimes use that to prevent certain areas from being built on. You can remove them from the map if you want to build there.
Trees might get some support, it certainly is annoying when you cant build a tower because a sapling just appeared there.

**Comment by LordHansCapon** [comment]
**Included camels and shields along with Neutral owner check:**
https://we.tl/t-TuNLQi8hmb

**Comment by Krarilotus** [comment]
tested with SHC and SHC-E, works well and as intended
-> only troops that can walk walls get overbuild by walls
-> tested all troop types
-> tested all buildign types
-> tested nearly to all worker types
-> camels also can get overbuild, deer and rabbits can't.
-> neutral and enemy workers can't get overbuild
-> troops still block AI#s from overbuildign them, your units are safe!
-> beware, units overbuild by unwalkable tiles (like double crenelation, corners of towers etc) will despawn and count as dead.

**Comment by GRhin** [comment]
This causes desync in multiplayer when units are raised onto a tower/wall. 
Krarilotus has more info

**Comment by LordHansCapon** [comment]
Well it obviously does, as something else happens than in vanilla, everyone has to have it enabled. If everyone has it enabled, then maybe the latency causes this desync.

**Comment by GRhin** [comment]
Fairly certain everyone had it enabled. @Krarilotus should be able to confirm.

**Comment by GRhin** [comment]
OK, just tested it with krarilotus, we both definately had it installed.
When one player over builds troops, the other player crashes out.

**Comment by JuGGerNaunT** [comment]
> When one player over builds troops, the other player crashes out.

Nice feature. If you don't want to lose, just use it and blame your opponent xD

**Comment by LeSpec** [comment]
CurrentlySelectedBuilding is not equal in Multiplayer. Instead the value from the "task list" should be used. 
The byte is at: 01959DF2 + 4f8 * [0194AF8C]

Task list holds values for every player action that also affets other players.
01959DF2        base value
4f8                   gap between tasks
[0194AF8C]     id of task being processed (0,...,c8)

Bildschirmfoto 2021-01-09 um 19 33 01

**Comment by GRhin** [comment]
Would this area also help with the small wall bugfix not working in
multiplayer?

**Comment by LeSpec** [comment]
I will take a look at it

**Comment by LeSpec** [comment]
So, about that BuildingType:
The current fix is inside the function CheckSpace (4F9A60) which gets called from at least 4 functions. One of them being CheckCanBuild (5037B0).
CheckCanBuild is used on UI level and on game level. It has the BuildingType in it's parameter list.
Im suggesting to just use that one since it's independent.

**Comment by Heroesflorian** [comment]
Great to see people work together to hopefully fix this soon for multiplayer! :)

But on a different note: Would it be possible to make the change (overbuilding units when placing buildings) dynamically toggleable ingame? 
More precisely, I would love to see the changed behaviour only be active when having CTRL (or SHIFT) pressed while placing a building (or be active by default, unless those keys are pressed). 

That way you could avoid falling into the same trap as the AI, which is overbuilding a ton of currently important (*) units accidentally while placing a farm or cathedral or whatever else in a hurry, while still being able to overbuild units when you intend to / do not care about those units. 
(* Depending on the situation, even a single stone delivery or a few horse archers passing by can be of game changing importance, or a whole bunch of workers and/or archers may be less important than placing something quickly.)

**Pull request merged**
