### PR TITLE
Fix AI crusader archers not lighting pitch

### PR DESCRIPTION
**Pull request by LordHansCapon**
Fixes the AI crusader archers not lighting pitch like arabian archers do when enemy units get onto it.

Test build available here:
https://we.tl/t-B3kAMj3dJC

Zip content:

- UnofficialCrusaderPatch.dll (38 287 360 bytes)
- UnofficialCrusaderPatchGUI.exe (122 368 bytes)

See #172

### CODE REVIEW

**Comment by Krarilotus** [comment]
tested by Xander10alpha

**Comment by LordHansCapon** [comment]
WeTransfer link update:
https://we.tl/t-Okbv4OKhTP

**Comment by J-T-de** [comment]
Can confirm: The Abbot uses his pitch, seems like it is working as intended :thumbsup:

**Review by Krarilotus — APPROVED** [review]
looks good! there is no unecessary clutter, change is straight down to the point!

**Pull request merged**
