### PR TITLE
Fix Lord animation freeze

### PR DESCRIPTION
**Pull request by LordHansCapon**
Fixes the lord animation freezing when they stop moving and when they destroy a building.

**Test build:**
https://we.tl/t-rxp2NHMwjz

### CODE REVIEW

**Comment by Monsterfisch** [comment]
tested on shc extreme  and seems to work no issue

**Comment by GRhin** [comment]
Oh, I just thought that was the big axe getting stuck in the ground lol. Didnt realise it was a bug.

**Comment by patel-nikhil** [comment]
Needs to be tested on regular crusader before being merge-ready

**Comment by Krarilotus** [comment]
tested with arabian lord and european lord on both crtusader normal and extreme. It seems like the animation doesn't finish however, and just resets. But that is probably as intended. It just wierdly lets the lord snap back to normal stance after finishing killing a building for example. Also tested with AI, which has no difference after moving lord around from killing archers firing at lord.

**Comment by LordHansCapon** [comment]
@Krarilotus sadly there is no "return" animation, so all I could do is snap it back into standing frame. Still better than letting it at the last frame of the attack animation in my opinion.

**Pull request merged**
