### PR TITLE
Added Armory/Marketplace weapon order fix option.

### PR DESCRIPTION
**Pull request by LordHansCapon**
The Armory and Marketplace has different weapon orders which is really confusing. This option fixes these orders.

Before:
https://imgur.com/a/beoK5Kt

After:
https://imgur.com/a/LXk0aSH

### CODE REVIEW

**Comment by Krarilotus** [comment]
is the option not ticked by default? as i imagine people would probably be used to how it is right now. I could also imagine people would like more the order of the market place, as thats likely to be used more often than the armoury for trading anyways, to be the default.

**Comment by BennyS93** [comment]
Hi

**Comment by BennyS93** [comment]
Nice Work LordHansCapon,
can you message me via Discord? I got a few questions.
Just sent a request BennyS#4152
Greetings

**Comment by LordHansCapon** [comment]
> is the option not ticked by default? as i imagine people would probably be used to how it is right now. I could also imagine people would like more the order of the market place, as thats likely to be used more often than the armoury for trading anyways, to be the default.

I think I set it as NOT default when installing. It also changes the order in the buying interface of the Marketplace, not just its trade weapons interface. So for example, when you are buying a Leather Armor, you can see the Mace to the left and the Crossbow to the right.

**Comment by Krarilotus** [comment]
i think he ment it as: could you plsssss send a friendrequest.

I hope sh0wdown reacts to it. I have promised him to not just take over and let changes get through without his permission. He just gave me rights to write stuff into the wiki. But i am sure, he ll definitly accept this change :D
I look forward to more, and still checking out your tutorial and all.

Tho pretty occupied with other projects right now...

**Comment by BennyS93** [comment]
You're right Krarilotus, i want to change a few things and need a little bit help with it :)
Which tutorial du you mean Krarilotus?
Greetings

**Comment by Krarilotus** [comment]
@BennyS93 LordHans made aTutorial on how to contribute to the project.
#488 you can check it here or go to the wiki and find it there aswell.

**Pull request merged**
