### PR TITLE
Fix moat digging units disappearing

### PR DESCRIPTION
**Pull request by LordHansCapon**
Fixes the bug where moat diggers would disappear randomly while digging.

**Note that they can still disappear if you order them to move while digging and they happen to stand on an unwalkable tile!**

Test build available here:
https://we.tl/t-P4eoUs3MX7

Zip content:
- UnofficialCrusaderPatch.dll (38 287 360 bytes)
- UnofficialCrusaderPatchGUI.exe (122 368 bytes)

See #222

### CODE REVIEW

**Comment by LordHansCapon** [comment]
WeTransfer link update:
https://we.tl/t-XqE4HO8xx2

**Comment by J-T-de** [comment]
Mr. Spearman just digged the entire moat of the Marshal without entering the void. Amazing!

**Comment by Krarilotus** [comment]
Digging moat does work flawlessly for digging it out, but it seems like the despawning still happens for digging it up, as in filling it in. Not sure why tho. I just tested with nizar and both our slaves didn't despawn, same for other units i dested, when digging out our own moats. Then i killed all his troops, sacrificed a lot of units to killing pits and started filling his moat, where slaves constantly kept disappearing as usual.

**Review by Krarilotus — COMMENTED** [review]
is all good, no unecessary lines

**Pull request merged**
