### PR TITLE
Separated changes into files and Extreme version for Mods

### PR DESCRIPTION
**Pull request by LordHansCapon**
Separated all the changes from Version.changes list into their own classes for easier readability and maintainability.

Also added GlobalLabels.

BinAlloc now accepts a third parameter: **isGlobal** . If set to true, the label will be pushed into a global label collection, which then can be used via **BinRefTo**.

An example usage:
Allocate some variables and label them with BinAlloc in a "Change" block. Set the third parameter to true, then access this label (address) via BinRefTo. See _**Mod_Change_Other_PlayerColorChange**_ class for an example.

### CODE REVIEW

**Comment by Krarilotus** [comment]
can we test the built somehow?
i d like to get other Dev's oppinions on this :)

**Comment by patel-nikhil** [comment]
@LordHansCapon @Krarilotus 
I approve of refactoring the changes to be defined outside of the Version.cs file and within their own file. The addition of GlobalLabel class within the Patching namespace is logical as it allows the potential for accessing labels defined in one change from another; furthermore this ability is already mimicked by the LabelCollection used by changes.

- There are a couple potential next steps made possible by this, such as (as I briefly discussed with LordHansCapon in the UCP discord) the potential to include separate changes based on version (crusader vs extreme).

There was as mentioned a change to the PlayerColorChange (now defined in ```Mod_Change_Other_PlayerColorChange.cs```) that will need to be tested.

I have verified through my testing that applying the other changes (except for multiplayer speed and strongholdify) in the Bugfixes, AI Lords, Units and Other tabs produce identical executables to the latest build of master. The two options i did not apply, I visually ensured that there was no change to them.

[UCP-PR-591.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/4496118/UCP-PR-591.zip)

**Comment by LordHansCapon** [comment]
I have updated the PullRequest with the addition of Extreme changes for mods. Version.changes no longer exists either, it is now changed to Version.Modifications, it only holds the modifications, thus some of the other parts of the program also got changed to follow this change.

**Comment by patel-nikhil** [comment]
A minor thing; it would be better practice I believe to make the fields `change` and `extremeChange` readonly within the Mod class, and for mod instances where the extreme change is identical to the normal crusader change it should return the property `Change` rather than the field `change`.

Overall looks great and functions as expected.

**Comment by LordHansCapon** [comment]
New changes:
- Added player color selector to identity menu with text.
- Revamped o_playercolor_ingame binary edit to use PlayerColorChosen variable.
- CreateExtremeChange now returns the Change property instead of the change field in Mods where Extreme is identical to the normal.

**Pull request closed without merging**
