### PR TITLE
Hungarian Translation

### PR DESCRIPTION
**Pull request by Liegav**
Here is my translation into Hungarian

### CODE REVIEW

**Comment by Krarilotus** [comment]
as we also have AIC files with descriptions in them aswell as custom start troops and start resource files, we will probably wait until the 2.15 release for a full hungarian translation. Until then, wellcome on board, and i hope you can join our discord (link in the read.me on t he main page).

**Comment by Krarilotus** [comment]
ah noo don't close it :O I was about to merge it after the release of 2.14 which is coming up shortly!

**Comment by Krarilotus** [comment]
you might want to update to master and translate the rest of the language file. But no need now, as we will change the GUI in 2.15 and will probably need more text translated. stay in touch :) But for making the hungarian translation valid for the current patch, it would need all the little blocks added in the 2.14 section :)

**Comment by Liegav** [comment]
Ok, thanks for the info.

**Comment by Liegav** [comment]
I replaced the project files from local, by me it runs now without error. I hope this helps now.

**Comment by Krarilotus** [comment]
hungarian translation works

**Pull request merged**
