### PR TITLE
UCP initial refactor

### PR DESCRIPTION
**Pull request by patel-nikhil**
Refactor UCP removing the GUI creation code from the Console project and using WPF xaml for GUI and moving the config to json (backwards compatibility for ucp.cfg to be re-implementing, marshalling the data to the UCPConfig data type).

### CODE REVIEW

**Comment by patel-nikhil** [comment]
[configs.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/5470876/configs.zip)

**Comment by patel-nikhil** [comment]
Schema for the ucp.json file (the config for changes)
[configschema.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/5470888/configschema.zip)

**Comment by patel-nikhil** [comment]
Key aspects of PR that need to be looked at:

- [ ] AIV installation

- [ ] Backwards compatibility with ucp.cfg

- [ ] Error handling

- [ ] Add key/value pair for auto-saving of config preference to prefs.json

- [ ] Some strings will need translation

**Comment by patel-nikhil** [comment]
[newgui.zip](https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/5498831/newgui.zip)
Note that the License.md is for JSON.Net and can be included in the source instead.

**Comment by patel-nikhil** [comment]
Todo List: 
- [ ] Add remaining languages and missing translations

**Comment by Krarilotus** [comment]
The default config could be taken from the previous UCP version, minus some boxes that overwrite aic parameters potentially (fixing reinforcements of defence troops)

**Comment by patel-nikhil** [comment]
# (Non-exhaustive) Changeset

## Language

- Language can now be changed while on the Main Window by selecting Option -> _&lt;Desired Language&gt;_ from the shown dropdown

## Path Selection

- Path selection can now be made both in the startup window and the Main Window using a dropdown with optional autocomplete, or by clicked `Browse` button
- On the startup window the `OK` button will not be clickable until a valid path is selected
- When a configuration file is loaded, and loading will result in a change of path (based on the user's _Preferences_) then a message box with options `Yes`, `No`, `Cancel` will be shown asking the user whether they wish to change the path

## Configuration

- UCP will continue to load the existing ucp.cfg format
- UCP is able to export the configuration from the Main Window by clicking File -> Save Config
  - The configuration will be exported in json format
- UCP is able to load a configuration from the Main Window by clicking File -> Load Config
  - The configuration to load should be in json format

- Configuration is handled in separate but similar manner by the UnofficialCrusaderPatchCLI.exe and UnofficialCrusaderPatchGUI.exe
  - For UnofficialCrusaderPatchGUI:
    - If `ucp.json` file exists in same directory as the UnofficialCrusaderPatchGUI.exe it will be loaded on startup
    - If `ucp.json` does not exist and _Preferences_ file contains key `mostRecentConfiguration` with value belonging to a valid filename then this configuration will be loaded
    - If neither of the above is true and `ucp.cfg` exists then this configuration will be loaded
    - If no configuration is present the UCP will load with an empty configuration
  - For UnofficialCrusaderPatchCLI:
    - If `--cfg=<filename>` is specified then the file pointed to will be used
    - If `--cfg` argument is not specified then `ucp.json` will be used if present in same directory
    - If neither of the above is true and `ucp.cfg` is present then the `ucp.cfg` will be loaded
    - If no configuration is present then the `Configuration file not found` will be written to console

## Preferences 
The _Preferences_ file is expected to contain the following keys and is not meant to be shared between users. Format is json with keys and values as follows:
- `hash`: _string_ - unique to a computer
- `path`: _string_ -- path to SHC installation folder
- `mostRecentConfiguration`: _string_ - used as defined in the **Configuration** section, this is updated only when a configuration is **loaded** and not when a configuration is saved
- `knownPaths`: _list&lt;string&gt;_ - list of previously selected paths, used in path selection dropdown, updated when a new path is selected
- `preferPathInConfig`: boolean - when present and set to `true` then UCP will use the path from the loaded config file, if the contained path is valid and the `hash` value of the config matches the `hash` value in the _Preferences_ file
- `language`: string - language to be used by the UCP, automatically updated when changed in the GUI
- `autosave`: boolean - when present and `true` then changes made in the GUI will be automatically written to `ucp.json` file.


# Implementation Details

## Language

### Location

- Localized strings for individual changes and GUI elements are now located within the UnofficialCrusaderPatchGUI project
- Instead of text files xaml resource files (in xml format) are used with format `<system:String x:Key="identifier">value</system:String>` where `identifier` is the key for retrieving the localized string from the GUI element, and `value` is the display value

### Using localized strings
- Within the GUI localized strings are used via the following example markup code `{DynamicResource ui_Bugfix}`

### Misc
- Preferred language is stored in the _Preferences_ file
- The strings for descriptions for AIC, AIV, StartTroop, StartResource changes are parsed and retrieved by the UnofficialCrusaderPath.dll
  - It is the responsibility of the content creator (UCP team for embedded content) to provide descriptions in the correct format (unchanged from v2.14)

## Configuration

The json schema for the configuration file can be found at this location: https://github.com/Sh0wdown/UnofficialCrusaderPatch/files/5470888/configschema.zip


## Backend - UnofficialCrusaderPatch.dll

Class `ModAPIContract` provides the API for interacting with the UnofficialCrusaderPatch library

Methods:
- `ListAICConfiguration`: List&lt;AICConfiguration&gt;
  - Reads embedded AIC files and AIC files in `resources\aic` folder and returns an `AICConfiguration` object containing: { Identifier, CharacterList, CustomCharacterList, Description }

- `SetAICConfiguration`
  - Sets the AIC configuration value based on the object provided
  - The parameter can be of type `String`, `Dictionary<string, object>[]`, `List<AICConfiguration>`
    - When string, it must correspond to the AIC filename (without extension)


- `ListAIVConfiguration`: List&lt;AIVConfiguration&gt;
  - Reads embedded AIV files and AIV folders in `resources\aiv` folder and returns a list of `AIVConfiguration` objects containing: { Identifier, Description }

- `SetAIVConfiguration`
  - Sets AIVConfiguration using value provided


- `ListStartResourceConfigurations`: Dictionary&lt;string, StartResourceConfiguration&gt;
  - Reads embedded StartResource json files and files in `resources\goods` folder and returns a list of `StartResourceConfiguration` objects containing: { Identifier, Description }

- `SetStartResourceConfiguration`
  - Sets StartResourceConfiguration using value provided

- `ListStartTroopConfigurations`: Dictionary&lt;string, StartTroopConfiguration&gt;
  - Reads embedded StartTroop json files and files in `resources\troops` folder and returns a list of `StartTroopConfiguration` objects containing: { Identifier, Description }

- `SetStartTroopConfiguration`
  - Sets StartTroopConfiguration using value provided

- `ListChanges`: Dictionary&lt;string, IEnumerable&lt;string&gt;&gt;
  - Returns the list of generic changes
  - The dictionary key is the Mod identifier, and the values are the list of identifiers for the Changes within the Mod

- `SetModValues`, `SetModExtremeValues`: IEnumerable&lt;ChangeConfiguration&gt;
  - Applies to Mod.Change and Mod.ExtremeChange respectively
  - Enables each Mod identified by the ChangeConfiguration, and contained SubChanges for - setting Change parameter value as applicable
  - Disables all Mods and Changes not specified

- `Install`: UCPConfig, overwrite, graphical
  - Installs the UnofficialCrusaderPatch
  - UCPConfig specifies the configuration to use
  - Installs AIV as specified in the _AIV Installation_ section (if included in the UCPConfig)
  
  - If the Crusader exe is present, UCP is installed to it
    - Installs AIC, StartResources, StartTroops, GenericMods (as included in the UCPConfig)

  - If the Extreme exe is present, UCP is installed to it
      - Installs AIC, StartResources, StartTroops, GenericMods (as included in the UCPConfig)

## AIV Installation

  - Installs AIV files first as follows, note that these steps and checks are in sequential order:
    - If the same AIV files exist in the SHC installation, and the UCP path then no action is taken, _AIV installation complete_
    - If `overwrite` is specified and `true` then all AIV files in the SHC installation folder will be deleted and new AIV files copied to the SHC installation folder, _AIV installation complete_
    - If an existing subfolder named `original` does not exist in the SHC installation `aiv` folder
      - Create subfolder `original`
      - Copy all files from SHC `aiv` folder to `original` folder
      - Copy new AIV folder contents to SHC `aiv` folder
    - If subfolder `original` exists in the SHC installation `aiv` folder:
      - If files in the SHC `aiv` folder and `original` folder are identical, delete all AIV files from the `aiv` folder
      - If the files are different:
        - If parameter `graphical` is true:
          - UnofficialCrusaderPatch has been called by UnofficialCrusaderPatchGUI, show MessageBox with prompt `aiv_prompt`. If `Yes` then delete AIV files from `original` and write AIV from SHC `aiv` folder to `original` folder. If `No` then delete AIV from SHC `aiv` folder. If `Cancel` throw an Exception and install fails with no modifications made.
    - The final step of all paths (where no exception is thrown) is copying the embedded AIV files or external AIV folder content to the SHC `aiv` folder

## Uninstallation

Restores the original Crusader/Extreme exe's (saved as `Stronghold Crusader.exe.ucp_backup` and `Stronghold_Crusader_Extreme.exe.ucp_backup` where present) - unchanged behaviour

[TODO!!] Restores AIV from the `original` subfolder of the SHC `aiv` folder, when `original` subfolder is present and non-empty

**Pull request closed without merging**
