### PR TITLE
Created a GitHub Actions specification for Continuous Integration

### PR DESCRIPTION
**Pull request by gynt**
Provides easy access to the latest version (or PR) with new features that are to be tested.

### CODE REVIEW

**Comment by Krarilotus** [comment]
does this need the evrey castles to compile? As currently we can still not compile without downloading the evrey castles extra.

**Comment by gynt** [comment]
> does this need the evrey castles to compile? As currently we can still not compile without downloading the evrey castles extra.

Yes, I had to init the git submodules (SHC_AIV). This spec basically builds exactly what is specified in the .sln and .csproj files.

**Comment by patel-nikhil** [comment]
Looks great! And I can see the successful build [here](https://github.com/gynt/UnofficialCrusaderPatch/actions).

**Comment by Krarilotus** [comment]
Is there also a success full build with the current state of the UCP?
@gynt you said this needs the evrey castles. So as the evrey castles are not part of the code here, how does it then handle the compile? You said you initialized submodules, but that was on your side of the code? Wouldn't this also need a commit of the evrey castles alongside it to function? And did you only build this with the new GUI or does this work with how the project is setup right now at this very moment?

**Comment by gynt** [comment]
@Krarilotus 
The handling of the evrey castles is not up to me. This pull request only achieves building the github repository into Debug and Release binaries (basically just runs the command `msbuild`). How the compiling is achieved is specified in the .sln file. 

There are three situations in which it builds new binaries: when there is a pull request to the master branch, when something is committed to the master branch, and when a repository owner clicks "build" manually.

It works with the new GUI and the old project setup.
This build is featuring the new GUI: https://github.com/gynt/UnofficialCrusaderPatch/actions/runs/383159872
This build is with the old GUI: https://github.com/gynt/UnofficialCrusaderPatch/actions/runs/383156878

**Comment by patel-nikhil** [comment]
AIV installation works fine, I downloaded build artifact, ran, and installed the UCP from it. No issue with the GUI or CLI exe

**Comment by Krarilotus** [comment]
I still don't get why it works tho. As when i run ms build locally it also crashes.

**Pull request merged**
